name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello! Thank you for opening an issue with us, it shall be reviewed as soon as possible"
        pr-message: "Thank you for submitting a PR to ths repo, kindly wait for the maintainer to review it and provide feedback"
